FROM golang:1.23.2-alpine

RUN apk add --no-cache curl

WORKDIR /backend

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN chmod +x ./closeTestDbAfterTests.sh

# The CMD is the entrypoint in docker compose